[package]
name = "day10test"
version = "0.1.0"
edition = "2021"

# 👇 here !
[lib]
crate-type = ["cdylib"]

[dependencies]
nom = "7.1.1"
wasm-bindgen = "0.2"

[dev-dependencies]
pretty_assertions = "1.3.0"
